### PR TITLE
fixes issue #93 by passing correctly imag_threshold when checking Hloc

### LINKED ISSUE #93: cthyb crashes by saying Delta(infty) is not real
I am trying to reproduce the results of https://journals.aps.org/prb/abstract/10.1103/PhysRevB.95.214119, which were obtained last year using git master of TRIQS v1.4 series.

In LiVO2, the V 3d Hamiltonian has large off-diagonal terms due to on-site e_g-e_g overlaps. However, the output of dmftproj shows that there are no imaginary terms in the Hamiltonian.

I modified the script that I used for TRIQS v1.4 to reflect the changes in the API for TRIQS v2.0. The script is attached. The h5 file after Wein2kConverter is run is also attached, in case you want to run the thing by yourselves. [The extension log is used because github does not seem to allow attaching python files.]

[LiVO2-el1-py.log](https://github.com/TRIQS/cthyb/files/2139262/LiVO2-el1-py.log)
[LiVO2-el1-h5.log](https://github.com/TRIQS/cthyb/files/2139282/LiVO2-el1-h5.log)

The script crashes with the following error:
```
Traceback (most recent call last):
  File "LiVO2-el1.py", line 124, in <module>
    S.solve(h_int=h_int, **p)
  File "/home/subedi/softwares/TRIQS-2.0-git/install/lib/python2.7/site-packages/triqs_cthyb/solver.py", line 130, in solve
    solve_status = SolverCore.solve(self, **params_kw)
Traceback (most recent call last):
  File "LiVO2-el1.py", line 124, in <module>
    S.solve(h_int=h_int, **p)
  File "/home/subedi/softwares/TRIQS-2.0-git/install/lib/python2.7/site-packages/triqs_cthyb/solver.py", line 130, in solve
    solve_status = SolverCore.solve(self, **params_kw)
RuntimeError: .. Error occurred at Wed Jun 27 00:44:14 2018

.. Error .. calling C++ overload 
.. solve() -> void 
.. in implementation of method SolverCore.solve
.. C++ error was : 
.. Triqs runtime error at /home/subedi/softwares/TRIQS-2.0-git/cthyb.src/c++/triqs_cthyb/solver_core.cpp : 126

Delta(infty) is not real. Maximum imaginary part is 1.19357e-06
.. Error occurred on node 1
```
I am not sure what has changed between versions 1.4 and 2.0 in CTHYB that the same input crashes the program.

Best,
Alaska

### PR DESCRIPTION
**Pull request by the-hampel**
fixes #93 by passing correctly imag_threshold when checking Hloc for imag elements, and providing a more useful error message

### CODE REVIEW

File: c++/triqs_cthyb/solver_core.cpp [hunk 1]
```diff
@@ -129,17 +129,18 @@ namespace triqs_cthyb {
       for (auto const &iw : Delta_iw[0].mesh()) Delta_iw_bl[iw] = iw - Delta_iw_bl[iw];
 
     // Compute the constant part of Delta
+    double imag_threshold = params.imag_threshold;
```
Comment (Wentzell) [inline c++/triqs_cthyb/solver_core.cpp]:
```suggestion
```

File: c++/triqs_cthyb/solver_core.cpp [hunk 2]
```diff
@@ -129,17 +129,18 @@ namespace triqs_cthyb {
...
     Delta_infty_vec = map(
        // Compute 0th moment of one block
-       [](gf_const_view<imfreq> d) {
+       [imag_threshold](gf_const_view<imfreq> d) {
```
Comment (Wentzell) [inline c++/triqs_cthyb/solver_core.cpp]:
```suggestion
       [imag_threshold = params.imag_threshold](gf_const_view<imfreq> d) {
```

**Review by Wentzell — CHANGES_REQUESTED** [review]

File: c++/triqs_cthyb/solver_core.cpp (hunk 1 above)
Comment (the-hampel) [reply c++/triqs_cthyb/solver_core.cpp]: applied these changes

File: c++/triqs_cthyb/solver_core.cpp (hunk 2 above)
Comment (the-hampel) [reply c++/triqs_cthyb/solver_core.cpp]: applied these changes

**Review by Wentzell — APPROVED** [review]
